[package]
name = "thumbcache"
version = "0.1.0"
edition = "2024"

[dependencies]
filetime = "0.2.25"
hex = "0.4.3"
image = "0.25.6"
sh2 = "0.1.0"
sha2 = "0.10.8"
tempfile = "3.19.1"
thiserror = "2.0.12"
