[package]
edition.workspace = true
license.workspace = true
name = "rsyfs"
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]

[lints]
workspace = true
